/**
 * Matrimonial App Backend — One-time setup script
 * Run with: npx tsx scripts/setup.ts
 *
 * Generates cryptographically secure secrets and writes backend/.env
 * Never run this again after going to production — it will overwrite your secrets.
 */

import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import readline from 'readline';

// ─── Helpers ──────────────────────────────────────────────────────────────────

function generateHex(bytes: number): string {
  return crypto.randomBytes(bytes).toString('hex');
}

function ask(rl: readline.Interface, question: string): Promise<string> {
  return new Promise((resolve) => rl.question(question, resolve));
}

function printSection(title: string): void {
  console.log('');
  console.log(`  ── ${title} ${'─'.repeat(Math.max(0, 50 - title.length))}`);
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  const envPath = path.resolve(__dirname, '../.env');

  console.log('');
  console.log('╔══════════════════════════════════════════════════════╗');
  console.log('║        💍 Matrimonial App Backend — Setup Script      ║');
  console.log('╚══════════════════════════════════════════════════════╝');
  console.log('');

  // ── Warn if .env already exists ───────────────────────────────────────────
  if (fs.existsSync(envPath)) {
    const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
    const answer = await ask(
      rl,
      '  ⚠️  backend/.env already exists. Overwrite it? (yes/no): '
    );
    rl.close();

    if (answer.trim().toLowerCase() !== 'yes') {
      console.log('  Aborted. Your existing .env was not changed.');
      process.exit(0);
    }
  }

  // ── Collect admin credentials interactively ───────────────────────────────
  const rl2 = readline.createInterface({ input: process.stdin, output: process.stdout });

  printSection('Admin Account');
  console.log('  These credentials are used to log in to the admin panel.');
  console.log('  Store them securely — they will be written to .env\n');

  const adminEmail    = (await ask(rl2, '  Admin email    : ')).trim();
  const adminPassword = (await ask(rl2, '  Admin password : ')).trim();

  rl2.close();

  if (!adminEmail || !adminPassword) {
    console.error('\n  ❌ Admin email and password are required. Aborting.');
    process.exit(1);
  }

  if (adminPassword.length < 12) {
    console.error('\n  ❌ Admin password must be at least 12 characters. Aborting.');
    process.exit(1);
  }

  if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(adminEmail)) {
    console.error('\n  ❌ Admin email does not look valid. Aborting.');
    process.exit(1);
  }

  // ── Generate secrets ───────────────────────────────────────────────────────
  printSection('Generating Secrets');

  const jwtSecret      = generateHex(64);   // 128 hex chars = 512 bits
  const encryptionKey  = generateHex(32);   // 64 hex chars  = 256 bits

  console.log('  ✅ JWT_SECRET      generated (64 bytes / 128 hex chars)');
  console.log('  ✅ ENCRYPTION_KEY  generated (32 bytes / 64 hex chars)');

  // ── Write .env ─────────────────────────────────────────────────────────────
  printSection('Writing backend/.env');

  const envContent = `# ═══════════════════════════════════════════════════════════════
# Matrimonial App Backend — Environment Variables
# Generated by scripts/setup.ts on ${new Date().toISOString()}
# ⚠️  NEVER commit this file to git.
# ═══════════════════════════════════════════════════════════════

# ── Server ────────────────────────────────────────────────────
PORT=5000
NODE_ENV=development
FRONTEND_URL=http://localhost:5173

# ── Security (auto-generated — do NOT change) ─────────────────
JWT_SECRET=${jwtSecret}
JWT_EXPIRY=2h
ENCRYPTION_KEY=${encryptionKey}

# ── Admin credentials ─────────────────────────────────────────
ADMIN_EMAIL=${adminEmail}
ADMIN_PASSWORD=${adminPassword}

# ── Database (JSON file — no setup needed) ────────────────────
DB_FILE=./database.json

# ── SMTP (fill in via Admin Panel → Settings → Email) ─────────
# Or set here directly:
# SMTP_HOST=smtp.gmail.com
# SMTP_PORT=587
# SMTP_USER=your@gmail.com
# SMTP_PASS=your-app-password

# ── Elasticsearch (optional — leave blank to use in-memory) ───
ELASTICSEARCH_URL=
`;

  fs.writeFileSync(envPath, envContent, 'utf-8');
  console.log(`  ✅ Written to: ${envPath}`);

  // ── Print next steps ───────────────────────────────────────────────────────
  console.log('');
  console.log('╔══════════════════════════════════════════════════════╗');
  console.log('║                    ✅ Setup Complete                  ║');
  console.log('╚══════════════════════════════════════════════════════╝');
  console.log('');
  console.log('  Next steps:');
  console.log('');
  console.log('  1. Start the backend:');
  console.log('       npm run dev');
  console.log('');
  console.log('  2. Log in to the Admin Panel with your credentials.');
  console.log('');
  console.log('  3. Fill in the following via Admin Panel → Settings:');
  console.log('');
  console.log('     📧 SMTP / Email settings:');
  console.log('        smtp_host, smtp_port, smtp_user, smtp_pass');
  console.log('        smtp_from_name, smtp_from_email');
  console.log('');
  console.log('     💳 Payment gateway (Razorpay):');
  console.log('        key_id, key_secret, webhook_secret');
  console.log('');
  console.log('     🔥 Firebase (for push notifications):');
  console.log('        firebase_api_key, firebase_auth_domain');
  console.log('        firebase_project_id, firebase_storage_bucket');
  console.log('        firebase_messaging_sender_id, firebase_app_id');
  console.log('        firebase_vapid_key');
  console.log('');
  console.log('  4. For production, update FRONTEND_URL and NODE_ENV in .env');
  console.log('');
  console.log('  Setup complete. Fill in your SMTP and payment keys in the');
  console.log('  Admin Panel after starting the server.');
  console.log('');
  console.log('  ─────────────────────────────────────────────────');
  console.log('  ⚠️  WHITE LABEL REMINDER:');
  console.log('  After starting the server, log in to Admin Panel');
  console.log('  and go to Settings → Company Information to set:');
  console.log('    • App / Brand Name (changes everything instantly)');
  console.log('    • Support Email, Phone, Address');
  console.log('    • Company GST Number');
  console.log('    • Invoice Logo and Prefix');
  console.log('  ─────────────────────────────────────────────────');
  console.log('');
}

main().catch((err: Error) => {
  console.error('\n  ❌ Setup failed:', err.message);
  process.exit(1);
});
